# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eba4f6fa4197f6a47dd1e9fde2d1fd5c350554710e980383f98dd09222bb617844ed7a060ad5f3e53e6471e6885654cee2864bff8cc93dc72d6b03768bb41594

test:
  secret_key_base: 81b0464048ce89d16c0d3aab964c746a3164491ec3c80c404b4b058a5e4ce7ed175391040f74f0cd87261fdb1838316b034400c112ba20ce5692811efd157639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
